---
format: gfm
---

# PHS 7045: Advanced Programming

Welcome to Advanced Programming in R and HPC! You can find the syllabus [here](syllabus.md). Readings for the week can be found in the GitHub issues associated with them.

## Contents

```{r}
#| echo: false
#| warning: false
dat <- read.csv("pages.csv")
library(data.table)

urlpath <- "https://github.com/UofUEpiBio/PHS7045-advanced-programming"
urlraw  <- "https://UofUEpiBio.github.io/PHS7045-advanced-programming"

# Iterating through the weeks
weeks <- sort(unique(dat$week))
tab <- NULL
for (i in 1:nrow(dat)) {

  # Adding the entry to the table
  tab <- rbind(
    tab,
    with(dat[i,,drop=FALSE], data.frame(
      Week  = date,

      # Title of the week
      Title = fifelse(
        !is.na(issue),
        sprintf(
          "%s (Issue [%i](%s/issues/%i))",
          name, issue, urlpath, issue
          ),
        sprintf("%s", name)
      ),

      # Lecture links
      Lecture = if (lecture_source != "") {
        sprintf(
          "[slides](%s/week-%02i-slides.html) ([source](%s))",
          urlraw, week, lecture_source 
        )
        } else {""},

      # Lab links
      Lab = if (lab_source != "") {
        sprintf(
          "[lab](%s/week-%02i-lab.html) ([source](%s))",
          urlraw, week, lab_source 
        )
      } else {""}
      )
    ))

  if (!is.na(dat[i,,drop=FALSE]$extra) && (dat[i,,drop=FALSE]$extra != ""))
    tab[nrow(tab),]$Title <- paste(
      tab[nrow(tab),]$Title,
      dat[i,,drop=FALSE]$extra
    )

  # Copy the files
  if (file.exists(dat[i,,drop=FALSE]$lecture)) {
    invisible(file.copy(
      from      = dat[i,,drop=FALSE]$lecture,
      to        = sprintf("docs/week-%02i-slides.html", dat[i,,drop=FALSE]$week), 
      overwrite = TRUE
    ))
  }

  if (file.exists(dat[i,,drop=FALSE]$lab)) {
    
    invisible(file.copy(
      from      = dat[i,,drop=FALSE]$lab,
      to        = sprintf("docs/week-%02i-lab.html", dat[i,,drop=FALSE]$week), 
      overwrite = TRUE
    ))
    
  }

}

knitr::kable(tab, row.names = FALSE)
```

## Assignment workflow

The course instructors will distribute the materials in a single compressed file (usually zip) for each assignment. Once the assignment materials are
available, the students are required to do the following: 

1. Download the compressed file and extract its contents into an empty folder.

2. Initialize the folder as a git repository, add its contents, and make
   the first commit.

3. Create a new repository in Github.com (under your account) and push your local repo into it. The name of the repository should be [name of the compressed file]-[your GitHub username]

You can start working on your assignment! We recommend pushing your changes as much as possible (it is good practice). As soon as you finish your assignment, you will have to ping one of the instructors in your commit message, for example:

```sh
git commit -a -m "Assignment done @gvegayon and @chipmanj"
```

This way @gvegayon and @chipmanj will receive a notification about this assignment. Furthermore, we encourage you to use other GitHub resources, such as adding the URL of [GitHub issue]() regarding that assignment, for example, if you include the following link in your commit message:

```
git commit -a -m "Assignment done https://github.com/UofUEpiBio/PHS7045-advanced-programming/issues/17"
```

Issue #17 in the PHS7045 website will now include a link to your commit. A similar thing can be done by cross-referencing an issue; this is, if you create a new issue in your repository and include the same link (https://github.com/UofUEpiBio/PM566/issues/17), the issue will be shown in #17 as cross-referenced.

## Example

For week #3, we will distribute a zip file named `week3-assignment.zip`. Using the command line, you can do all the previous steps as follows:

```sh
cd ~
wget github.com/UofUEpiBio/PHS7045-advanced-programming/raw/master/assignments/week3-assignment.zip
unzip week3-assignment.zip -d week3-assignment-gvegayon
cd week3-assignment-gvegayon
git init
git add .
git commit -a -m "Initial commit"
```

You still need to go to Github.com to create the new repository. Assuming you do that successfully, we continue:

```sh
git remote add origin git@github.com:gvegayon/week3-assignment-gvegayon.git
git push -u origin master
```

And you are done!

