---
title: "Lab 06 - Parallel computing"
format:
  html:
    embed-resources: true
---

# Learning goals

* Learn from HW 1 and revisit vectorizing
* Parallel computing for simulations

# Lab task

**Part 1 (20 minutes)**:

Write an outline of [lab 2  / HW 1 solution](https://github.com/UofUEpiBio/PHS7045-advanced-programming-solutions).


Two people will present their outline.  After the first presenter, the second presenter will add any additional details/insights.

```{r,eval=FALSE}
set.seed(NULL)
sample(c("Daniel", "Eric", "Haojia", "Hyejung", "Kline", "Linda", "Ransmond", "Ravi"),2)
```


**Part 2 (30 minutes)**:

Re-write design 1 and/or design 2 based upon what you've learned/outlined from the solution.  Compare efficiency between your submission and your revision using the `bench` package.


**Part 3 (25 minutes)**:

Using either submitted design in HW 1 or revisions made in Part 2, use a parallelization method to simulate 1000 replicates.  Compare the timing to simulating the same 1000 replicates without parallelization.

Extra time? Take any next steps on completing the simluation from the original homework assignment:

* Assess the Type I error (increase the number of replicates)
* Refine $\delta$ as needed
* Simulate under the alternative hypothesis