---
title: "Advanced Programming with R: Final"
format:
  html:
    embed-resources: true
---

## Due date

The R package is due by the end of Tuesday December 10th. 

The in-class presentation will be Thursday, December 12th.

## Task

Expand upon midterm project with a new component and create an R package. The new component will be agreed upon on by Thursday November 21.

## Deliverables

* An extension of the midterm project and package creation (70% of grade).
* An oral presentation of no more than seven minutes (30% of grade).

## Requirements

The presentation:

 - The time allocation will be 7 minutes.

 - It Should be presented with slides (PowerPoint/quarto::revealjs/google slides/etc.)

 - It should have the following structure (roughly):

   a.  Review of the problem which highlights the issue or “why” the problem needs solving (may consider including visuals to highlight the issue; ~2 slides)

   b.  Overview of the package until the midterm (~1 slide)

   c.  The new feature of the coding solution (~ 1 slide each)

   d.  Provide a single example highlighting the package (~1-3 slides).

::: {.callout-tip}

(i) Fewer slides than minutes available; if not possible, make sure you spend less than a minute per slide (on average).
(ii) More figures and less text, *i.e.*, avoid paragraphs.
(iii) Avoid diving into the details (or at least, most of your talk should be to the general audience). 
(iv) Focus on what your audience would value the most.
(v) Cluttered slides are never good: It probably needs to be split if they are too long.
:::

```{r}
#| echo: false
fa <- fontawesome::fa("jedi-order")
```

The R package (May 4th `r fa`):

- Add a new function/feature to the R package using parallel computing or `Rcpp` (a must.)

- The package should pass `R CMD check`s using macOS, Ubuntu, and Windows for the R release and development versions (x6 `R CMD check`s). Notes are OK, but warnings are not. 

- The package should pass the `R CMD check` on Ubuntu using the R release version with the option [`--as-cran`](https://cran.r-project.org/web/packages/submission_checklist.html) (more strict `R CMD check`.)

- The package should have a vignette.



## Grading

The grade will be based on clear communication and coding.

# Misc

## Installing the package with the vignettes

You can install this package from the source using the following
commands from the command line:

``` bash
R CMD build .
R CMD INSTALL egpkg2024_1.0.tar.gz
```

The first command builds a tar.gz file that can be shared. This is what
you share when you submit to CRAN. The second command installs the
package in your computer. Notice that this approach builds the
vignettes, making them available to your R session. Recall you can
access vignettes using the `vignette` command like this:

``` r
vignette(package="dplyr")
```

Which will list the vignettes available to the dplyr R package (learn
more typing `?vignette` in your R console).
