name: Build and publish dev container

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/Dockerfile
      - .github/workflows/docker.yml
  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true
        default: latest
        type: string

permissions:
  contents: read

env:
  IMAGE_NAME: uofuepibio/phs7045-advanced-programming

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .devcontainer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'latest' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
