name: Examples

on: [push, pull_request]

jobs:
  test-ubuntu:
    runs-on: Ubuntu-latest
    container: ghcr.io/uofuepibio/phs7045-advanced-programming:fall2024

    steps:
      - uses: actions/checkout@v4

      - name: Execute
        run: |
          cd example-problems
          make README.md -B

      - name: Commit results
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git commit -a -m 'Re-build examples' || echo Nothing has changed
          git push origin || echo "No changes to commit"
