name: Render website

on: [push, pull_request]

jobs:
  upload:
    runs-on: Ubuntu-latest
    container: ghcr.io/uofuepibio/phs7045-advanced-programming:fall2024

    steps:
      - uses: actions/checkout@v4

      - name: preping
        run: |
          quarto render README.qmd --to=html
          mv README.html index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

  website:
    if: ${{ github.event_name != 'pull_request' }}
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4

      

