name: Render website

on: [push, pull_request]

jobs:
  quarto-ubuntu:
    runs-on: Ubuntu-latest
    container: ghcr.io/uofuepibio/phs7045-advanced-programming:fall2024

    steps:
      - uses: actions/checkout@v4

      - name: Render
        run: |
          make -B README.md

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add docs/* || echo Nothing to be added
          git commit -a -m 'Re-build examples' || echo Nothing has changed
          git push origin || echo "No changes to commit"

  website:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4

      

